dist: xenial # required for python >= 3.7

language: python

# sudo false implies containerized builds
sudo: false

python:
  - 3.6
  - 3.7

env:
  global:
    # package name for test invocation
    - PACKAGENAME="lasso_model"

install:
  - pip install -r requirements.txt

script:
  - pytest 
