dist: xenial # required for python >= 3.7

language: python

# sudo false implies containerized builds
sudo: false

python:
  - 3.6
  - 3.7

before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
  - pip install -r requirements.txt

script:
  - mkdir lasso_model/logs
  - python3 lasso_model/train_pipeline.py 
  - pytest 
